
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/CardManagementSystem"
    username: "postgres"
    password: "123"
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      show-sql: true
  liquibase:
    enabled: true



logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.orm.jdbc.bind: TRACE
server:
  port: 8080

token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
